name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build (optional)
      run: echo "No build step for static site"
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.deep1707 }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIARQZMZLQ55GGFQZ5J}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.v0oFEUTFl8iVJR33n6+UpOXzkNmeTuCTfhB0yVgW}}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: './'
